### ISSUE TITLE
unable to log in: invalid username "Email/Username is not valid" (RM #5925)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3897]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5925***
*Originally created by **Ulf Seltmann** at 2020-10-20 09:31:54 UTC.*

Since you closed #5924 without my response i have to open a new ticket.

using an email is not working either:

```
version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4:4.27
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "dev"
    ports:
    - 8080:80
```
